---
title: "Growth in changing environments"
author: "Andrew MacDonald"
description: |
  Approximations and simulated population growth when the environment fluctuates.
date: 11 Nov 2022
editor: visual
categories: [UdeS, stan]
draft: true
execute: 
  eval: false
---

```{r setup, eval=TRUE, message=FALSE, warning=FALSE}
library(targets)
library(ggplot2)
library(tidyverse)
library(tidybayes)
```

## What is this post

This post is meant to be a simple template for new posts -- when I make a new post I'll start by copying and pasting this current one over. Probably in the future there will be a plugin that does this for us, but until then this will be fine.

## Why I switched to Quarto

A simple and frequent answer: overenthusiasm! I like seeing all the new things that the Rstudio team develop, and I know that this vibrant community will keep adding features and tutorials

## quarto resources

-   [the Ultimate Guide to starting a Quarto blog](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.htm)

-   [quarto discussions](https://github.com/quarto-dev/quarto-cli/discussions)

-   [Danielle Navarro's comments on the topic](https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/)

-   [Nick Tierney's notes](https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/)

-   and of course [Nicks exciting book project!](https://rmd4sci.njtierney.com/)

## surprise it's targets

<iframe src="https://giphy.com/embed/12yB3XoYboAkjm" width="480" height="273" frameBorder="0" class="giphy-embed" allowFullScreen>

</iframe>

<p><a href="https://giphy.com/gifs/disney-2016-new-year-the-emperors-groove-12yB3XoYboAkjm">via GIPHY</a></p>

I'm also using [targets](https://github.com/ropensci/targets). Here are some observations on that so far:

-   `Last error: ! System command 'quarto' failed` I get this error message more that 10x more often than any other. As I'm learning Quarto I keep making errors which break the Quarto process but `targets` doesn't (yet?) communicate the specific error message. To find out what has gone wrong, I go over to the terminal and run `quarto render .`

-   you have to go into `_metadata.yml` and stop the posts from freezing, by setting `freeze: false` . Targets will handle all the rest of it.

I'm using `targets` with quarto because I want to work with large bayesian models fit with `stan` and `brms`., and fitting them in a regular blog post -- including compiling, sampling etc.

## My own observations and questions

so far it is very straightforward!

-   \~it seems like post folder cant begin with dates?\~ you *can* start a folder with a date, and I do, so that the posts sort in at least approximately the right temporal sequence. However the date for a post comes from the YAML, not the folder name.

-   love LOVE the bibliography automatically appearing

-   DO think about changing the working directory for chunk evaluations to the project root, [as described here](https://bookdown.org/yihui/rmarkdown-cookbook/working-directory.html). This is really important because that is the directory that `targets` uses when sourcing files. For example `tar_load(my_target_name)` will load in an object from your pipeline. But run this same line from an `.qmd` file in a subfolder (say `posts/yourpostname/index.qmd`), then THAT will be the location the computer looks in..
