---
title: How many groups is enough?
author: Andrew MacDonald
description: Simulations to see how many groups to use for a random effect
date: "3 June 2023"
editor: source
categories: [UdeS, stan]
execute:
  eval: false 
draft: true
---


```{r setup, eval=TRUE, message=FALSE, warning=FALSE}
library(targets)
library(ggplot2)
library(tidyverse)
library(tidybayes)
library(cmdstanr)
```

How many groups do you need for a random effect? 

let's prepare a data simulation where we are looking at just a few groups. 
We'll assume we're working with a classic ANOVA:

$$
\begin{align}
\text{measurement}_i &\sim \text{normal}(\mu_{\text{treatment}[i]}, \sigma) \\
\mu_{\text{treatment}} &\sim \text{normal}(\mu_{\text{overall}}, \sigma_{\text{treatment}}) \\
\mu_{\text{overall}} &\sim \text{normal}(14, 1) \\
\sigma_{\text{treatment}} &\sim \text{exponential}(1) \\
\sigma_{\text{treatment}} &\sim \text{exponential}(1) \\
\end{align}
$$

test the model
```{r}
test_ngroup <- 3
test_sgroup <- 1.3
test_groupmeans <- rnorm(n = test_ngroup, mean = 0, sd = .01)
test_groupIDs <- rep(1:test_ngroup, each = 42)
meas <- rnorm(n = length(test_groupIDs),
              mean = test_groupmeans[test_groupIDs],
              sd = 1.5)

plot(as.factor(test_groupIDs), meas)
```


look at the model

```{r}
#| class-output: stan

hier_intercept <- cmdstan_model(here::here("posts/2023-04-26-how-many-groups-is-enough/hier_intercept.stan"))

hier_intercept
```

fit it to this sample:
```{r}
hier_intercept_samples <- hier_intercept$sample(
  data = list(
    N = length(meas),
    Ngroup = test_ngroup,
    measurements = meas,
    group_id = test_groupIDs),
  refresh = 0
  )
```

```{r}
hier_intercept_samples
```


```{r eval = FALSE}
library(tidyverse)

nrep <- 5
group_sizes <- c(3, 13, 30, 300)
tibble(Ngroup = group_sizes,
       rep = 1:nrep
       

```

When groups are not different actually

# using a different parameterization

```{r}
k <- .8
q <- 200

curve(q/k*(1 - exp(-k*x)), xlim = c(0,20))

```

