---
title: "Twitter recommends stats books"
author: "Andrew MacDonald"
date: 02 Dec 2016
categories: [books, statistics, twitter]
description: 'What are my brilliant friends reading?'
---

Yesterday I asked my beloved Twitter nerds to recommend to me their favourite quantitative texts in Ecology:

<blockquote class="twitter-tweet" data-partner="tweetdeck"><p lang="en" dir="ltr">my postdoc super tells me I can BUY BOOKS! 💓📚📚💓 quick sweet friends, what are your fun statistical ecology book recommendations?</p>&mdash; Andrew MacDonald (@polesasunder) <a href="https://twitter.com/polesasunder/status/804480623410872320">December 2, 2016</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

As a way of saying **"Thank you!"** I thought that I would put all the books in a list for anyone who is curious.

### Stats texts

* [Statistics for Spatio-Temporal Data, by  Noel Cressie, Christopher K. Wikle, Wiley-Blackwell (19 avril 2011)](http://eu.wiley.com/WileyCDA/WileyTitle/productCd-EHEP002348.html)
* [Statistical Rethinking: A Bayesian Course with Examples in R and Stan by Richard McElreath](https://www.amazon.fr/Statistical-Rethinking-Bayesian-Course-Examples/dp/1482253445) -- This one was a HUGE favourite recommended by multiple people. Going straight to the top of my list!
* [Applied Hierarchical Modeling in Ecology: Analysis of distribution, abundance and species richness in R and BUGS, 1st Edition- by  Kery   &    Royle, Academic Press](http://store.elsevier.com/Applied-Hierarchical-Modeling-in-Ecology-Analysis-of-distribution-abundance-and-species-richness-in-R-and-BUGS/Marc-Kery/isbn-9780128014868/) on the strength of recs from two fine quantitative folks, Auriel Fournier and Petr Keil
* [Quantitative Ecology and Evolutionary Biology: Integrating models with data (Oxford Series in Ecology and Evolution) 1st Edition by Otso Ovaskainen, Henrik Johan de Knegt, Maria del Mar Delgado](https://www.amazon.com/Quantitative-Ecology-Evolutionary-Biology-Integrating/dp/0198714874)
* [ Bayesian Models - A Statistical Primer for Ecologists (Anglais) Relié – 25 août 2015 - de N Thompson Hobbs , Mevin Hooten ](https://www.amazon.fr/Bayesian-Models-Statistical-Primer-Ecologists/dp/0691159289%3FSubscriptionId%3DAKIAILSHYYTFIVPWUY6Q%26tag%3Dduckduckgo-ffsb-fr-21%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3D0691159289)
* [ Generalized Additive Models: An Introduction with R, Second Edition (Chapman & Hall/CRC Texts in Statistical Science) 2nd Edition by Simon N. Wood ](https://www.amazon.com/Generalized-Additive-Models-Introduction-Statistical/dp/1498728332)
* [Regression Modeling Strategies With Applications to Linear Models, Logistic Regression, and Survival Analysis by Harrell, Frank ](http://www.springer.com/us/book/9781441929181)
* [ Graph Theory and Complex Networks: An Introduction by Maarten van Steen ](https://www.amazon.com/Graph-Theory-Complex-Networks-Introduction/dp/9081540610/ref=sr_1_7?s=books&ie=UTF8&qid=1480639288&sr=1-7&keywords=%22graph+theory%22)
* [ Data Analysis Using Regression and Multilevel/Hierarchical Models 1st Edition by Andrew Gelman, Jennifer Hill ](https://www.amazon.com/Analysis-Regression-Multilevel-Hierarchical-Models/dp/052168689X) -- this one (which I had already) was another very frequent recommendation!


### Classic works:

* [ A Crude Look at the Whole: The Science of Complex Systems in Business, Life, and Society by John H. Miller](https://www.amazon.fr/Crude-Look-Whole-Science-Business-ebook/dp/B016TX4DU4%3FSubscriptionId%3DAKIAILSHYYTFIVPWUY6Q%26tag%3Dduckduckgo-ffab-fr-21%26linkCode%3Dxm2%26camp%3D2025%26creative%3D165953%26creativeASIN%3DB016TX4DU4)
* [Daedalus, or Science and the Future](https://www.amazon.com/Daedalus-Science-Future-J-Haldane/dp/B000RB32TI) by JBS Haldane
* [Evidence and Evolution: the Logic behind the Science](http://www.cambridge.org/catalogue/catalogue.asp?isbn=9780521692748) by Elliott Sober
* Biology as Ideology, Lewontin

So, as Margaret Kosmala of [Ec0l0gy b1ts](http://ecologybits.com/index.php/2016/11/30/how-to-run-an-online-academic-book-club/) says: what are we reading next?


```{r setup, eval=TRUE, message=FALSE, warning=FALSE}
library(targets)
library(ggplot2)
library(tidyverse)
library(tidybayes)
```

## What is this post

This post is meant to be a simple template for new posts -- when I make a new post I'll start by copying and pasting this current one over. Probably in the future there will be a plugin that does this for us, but until then this will be fine.

## Why I switched to Quarto

A simple and frequent answer: overenthusiasm! I like seeing all the new things that the Rstudio team develop, and I know that this vibrant community will keep adding features and tutorials

## quarto resources

-   [the Ultimate Guide to starting a Quarto blog](https://albert-rapp.de/posts/13_quarto_blog_writing_guide/13_quarto_blog_writing_guide.htm)

-   [quarto discussions](https://github.com/quarto-dev/quarto-cli/discussions)

-   [Danielle Navarro's comments on the topic](https://blog.djnavarro.net/posts/2022-04-20_porting-to-quarto/)

-   [Nick Tierney's notes](https://www.njtierney.com/post/2022/04/11/rmd-to-qmd/)

-   and of course [Nicks exciting book project!](https://rmd4sci.njtierney.com/)

## surprise it's targets

<iframe src="https://giphy.com/embed/12yB3XoYboAkjm" width="480" height="273" frameBorder="0" class="giphy-embed" allowFullScreen>

</iframe>

<p><a href="https://giphy.com/gifs/disney-2016-new-year-the-emperors-groove-12yB3XoYboAkjm">via GIPHY</a></p>

I'm also using [targets](https://github.com/ropensci/targets). Here are some observations on that so far:

-   `Last error: ! System command 'quarto' failed` I get this error message more that 10x more often than any other. As I'm learning Quarto I keep making errors which break the Quarto process but `targets` doesn't (yet?) communicate the specific error message. To find out what has gone wrong, I go over to the terminal and run `quarto render .`

-   you have to go into `_metadata.yml` and stop the posts from freezing, by setting `freeze: false` . Targets will handle all the rest of it.

I'm using `targets` with quarto because I want to work with large bayesian models fit with `stan` and `brms`., and fitting them in a regular blog post -- including compiling, sampling etc.

## My own observations and questions

so far it is very straightforward!

-   it seems like post folder can't begin with dates?

-   love LOVE the bibliography automatically appearing
